import {readFileSync,writeFileSync,readdirSync,mkdirSync,cpSync,existsSync,rmSync} from 'node:fs';
import {join} from 'node:path';
const e=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=s=>new Date(s+'T12:00:00Z').toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric',timeZone:'UTC'});
const issues=readdirSync('content').filter(n=>n.endsWith('.json')).map(n=>JSON.parse(readFileSync(join('content',n),'utf8'))).sort((a,b)=>b.date.localeCompare(a.date));
if(!issues.length)throw Error('At least one issue is required');
for(const i of issues){
 if(!/^\d{4}-\d{2}-\d{2}$/.test(i.date)||!i.stories.length||!existsSync(`public/downloads/${i.date}.docx`))throw Error('Incomplete issue');
 for(const s of i.stories){if(!s.sources.length||!s.paragraphs.length)throw Error('Missing story content');for(const r of s.sources)if(!/^https?:\/\//.test(r.url))throw Error('Invalid source URL');}
}
const latest=issues[0];
const num=i=>String(issues.length-issues.indexOf(i)).padStart(2,'0');
const wordCount=i=>i.stories.map(s=>s.paragraphs.map(p=>p.text).join(' ')).join(' ').split(/\s+/).length;
const mins=i=>Math.max(1,Math.ceil(wordCount(i)/180));
const route=i=>`/issues/${i.date}/`;
const arrow='<span aria-hidden="true">↗</span>';
const nav=active=>`<a class="skip" href="#main">Skip to content</a><header class="masthead"><a class="brand" href="/" aria-label="Founders Inflections home"><span class="brand-mark" aria-hidden="true">FI</span><span>Founders Inflections<span class="brand-sub">THE WEEKLY</span></span></a><nav aria-label="Main navigation"><a href="/" ${active==='latest'?'aria-current="page"':''}>Latest issue</a><a href="/archive/" ${active==='archive'?'aria-current="page"':''}>Archive</a></nav><span class="mast-note">A founder’s reading file</span></header>`;
const footer=`<footer><a href="/">Founders Inflections</a><span>New developments. Original sources. Every week.</span><a href="/archive/">Browse the archive ${arrow}</a></footer>`;
function shell(title,desc,body,active=''){
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(title)} | Founders Inflections</title><meta name="description" content="${e(desc)}"><link rel="icon" type="image/svg+xml" href="/favicon.svg"><link rel="stylesheet" href="/styles.css"></head><body>${nav(active)}${body}${footer}</body></html>`;
}
const meta=i=>`<span class="eyebrow">Issue ${num(i)}</span><span>${date(i.date)}</span><span>${i.stories.length} developments</span><span>${mins(i)} min read</span>`;
const tag=s=>`<span class="category">${e(s.category)}</span>`;
const storyCard=(s,n,i)=>`<a class="story-card" href="${route(i)}#story-${n+1}"><div class="card-top">${tag(s)}<span class="story-number">${String(n+1).padStart(2,'0')}</span></div><h3>${e(s.title)}</h3><p>${e(s.paragraphs[0].text)}</p><span class="card-bottom">Read the development ${arrow}</span></a>`;
const home=shell('Latest issue',latest.intro,`<main id="main"><section class="issue-head"><div class="meta">${meta(latest)}</div><div class="title-row"><h1>${e(latest.title)}</h1><div class="issue-intro"><p>${e(latest.intro)}</p><a class="button" href="${route(latest)}">Read this week’s issue <span aria-hidden="true">→</span></a><a class="text-link" href="/downloads/${latest.date}.docx" download>Download Word edition ↓</a></div></div></section><section class="developments" aria-labelledby="developments-title"><div class="section-top"><h2 id="developments-title">This week’s developments</h2><span>${new Date(latest.date+'T12:00:00Z').toLocaleDateString('en-US',{month:'long',year:'numeric',timeZone:'UTC'}).toUpperCase()}</span></div><div class="story-grid">${latest.stories.map((s,n)=>storyCard(s,n,latest)).join('')}</div></section><section class="archive-strip"><div><span class="eyebrow">The reading file</span><h2>Every week, kept in one place.</h2></div><a class="button outline" href="/archive/">Explore ${issues.length===1?'the first issue':issues.length+' issues'} <span aria-hidden="true">→</span></a></section></main>`,'latest');
const archive=shell('Weekly archive','Browse every issue of Founders Inflections.',`<main id="main"><section class="archive-head"><span class="eyebrow">The reading file</span><h1>The archive<span class="accent">.</span></h1><p>Go back a week. Follow what changed.</p><span class="archive-count">${issues.length} ${issues.length===1?'issue':'issues'} in the collection</span></section><div class="archive-list">${issues.map(i=>`<article class="archive-row"><div class="archive-date"><span class="eyebrow">Issue ${num(i)}</span><time datetime="${i.date}">${date(i.date)}</time></div><div><a href="${route(i)}"><h2>${e(i.title)} ${arrow}</h2></a><p>${e(i.intro)}</p><div class="archive-tags">${[...new Set(i.stories.map(s=>s.category))].map(c=>`<span>${e(c)}</span>`).join('')}</div></div><div class="archive-actions"><span>${i.stories.length} developments · ${mins(i)} min</span><a class="text-link" href="/downloads/${i.date}.docx" download>Word edition ↓</a></div></article>`).join('')}</div></main>`,'archive');
function detail(i){
 const ix=issues.indexOf(i),older=issues[ix+1],newer=issues[ix-1];
 return shell(i.title,i.intro,`<main id="main"><div class="back-row"><a href="/archive/">← All issues</a><a href="/downloads/${i.date}.docx" download>Download Word edition ↓</a></div><header class="reading-head"><div class="meta">${meta(i)}</div><h1>${e(i.title)}</h1><p>${e(i.intro)}</p><p class="coverage">${e(i.coverage)}</p></header><div class="reading-layout"><aside class="contents"><div class="sticky"><span class="eyebrow">In this issue</span><ol>${i.stories.map((s,n)=>`<li><a href="#story-${n+1}"><span>${String(n+1).padStart(2,'0')}</span>${e(s.title)}</a></li>`).join('')}</ol></div></aside><div class="articles">${i.stories.map((s,n)=>`<article class="story" id="story-${n+1}"><div class="article-kicker"><span class="story-number">${String(n+1).padStart(2,'0')}</span>${tag(s)}<time datetime="${s.eventDate}">${date(s.eventDate)}</time></div><h2>${e(s.title)}</h2>${s.paragraphs.map(p=>`<section><h3>${e(p.label)}</h3><p>${e(p.text)}</p></section>`).join('')}<div class="sources"><h3>Go to the sources</h3>${s.sources.map(r=>`<a href="${e(r.url)}" target="_blank" rel="noopener noreferrer"><span>${e(r.title)} ${arrow}<small>${e(r.date)}</small></span></a>`).join('')}</div></article>`).join('')}<nav class="issue-pagination" aria-label="Other issues">${older?`<a href="${route(older)}">← ${date(older.date)}</a>`:'<span>You’re at the first issue.</span>'}${newer?`<a href="${route(newer)}">${date(newer.date)} →</a>`:'<a href="/archive/">All issues →</a>'}</nav></div></div></main>`);
}
rmSync('dist',{recursive:true,force:true});mkdirSync('dist');cpSync('public','dist',{recursive:true});
function write(path,html){mkdirSync(join('dist',path),{recursive:true});writeFileSync(join('dist',path,'index.html'),html);}
write('',home);write('archive',archive);for(const i of issues)write(`issues/${i.date}`,detail(i));
writeFileSync('dist/404.html',shell('Page not found','This page does not exist.',`<main id="main" class="archive-head"><span class="eyebrow">404</span><h1>This page isn’t in the file.</h1><a class="button" href="/archive/">Browse the archive →</a></main>`));
// Verify every generated local page and download link resolves before publishing.
for(const html of [home,archive,...issues.map(detail)])for(const [,href] of html.matchAll(/href="(\/[^"#]*)(?:#[^"]*)?"/g)){if(!existsSync(join('dist',href))&&!existsSync(join('dist',href,'index.html')))throw Error('Broken internal link '+href);}
console.log(`Built ${issues.length+2} pages, ${issues.length} downloads. All internal links resolve.`);
